# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_key', models.CharField(max_length=250)),
                ('otp_key', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SignupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('Freemium', 'Freemium'), ('Starter', 'Starter'), ('Premium', 'Premium')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='confirmsignup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_signup.SignupModel'),
        ),
    ]
